In [1]:
from __future__ import print_function
import tabula
import re 
import csv
import os.path
import requests

import datetime
import os.path

from datetime import datetime
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

read = tabula.read_pdf("sche.pdf", pages='all')[0]
tabula.convert_into("sche.pdf", "Sche.csv", output_format="CSV", pages="all")

read

,Course,Sect.,Description,Credits,Instructor,Start Date,End Date,Grade,Location,Days and Times,Unnamed: 0
0,CIV 203,1.0,Ancient World: Humanities,3.0,"Monsma, Frederick",09/04/2022,12/01/2022,***,A-B1-08,MON 9:45am-11:15am,Lecture
1,NaN,NaN,NaN,NaN,"Monsma, Frederick",09/04/2022,12/01/2022,NaN,A-B1-08,WED 9:45am-11:15am,Lecture
2,ENG 101,3.0,Argument,3.0,"Danilovich, Stephen",09/04/2022,12/01/2022,***,A-B1-11,TUE 10:30am-11:30am,Lecture
3,NaN,NaN,NaN,NaN,"Danilovich, Stephen",09/04/2022,12/01/2022,NaN,A-B1-11,THU 10:30am-11:30am,Lecture
4,NaN,NaN,NaN,NaN,"Danilovich, Stephen",09/04/2022,12/01/2022,NaN,A-B1-11,SUN 10:30am-11:30am,Lecture
5,ENGR 344,1.0,Mechanics I,3.0,"Hassan, Aram",09/04/2022,12/01/2022,***,B-F2-31,TUE 1:00pm-2:00pm,Lecture
6,NaN,NaN,NaN,NaN,"Hassan, Aram",09/04/2022,12/01/2022,NaN,B-F2-31,THU 1:00pm-2:00pm,Lecture
7,NaN,NaN,NaN,NaN,"Hassan, Aram",09/04/2022,12/01/2022,NaN,B-F2-31,SUN 1:00pm-2:00pm,Lecture
8,ITE 202,1.0,IT System,3.0,"Lukwesa, Katongo",09/04/2022,12/01/2022,***,B-B1-01,MON 12:30pm-2:00pm,Lecture
9,NaN,NaN,NaN,NaN,"Lukwesa, Katongo",09/04/2022,12/01/2022,NaN,B-B1-01,WED 12:30pm-2:00pm,Lecture
10,STT 201,2.0,Statistics,3.0,"Nikpour, Mehdi",09/04/2022,12/01/2022,***,A-B1-42,TUE 9:15am-10:15am,Lecture
11,NaN,NaN,NaN,NaN,"Nikpour, Mehdi",09/04/2022,12/01/2022,NaN,A-B1-42,THU 9:15am-10:15am,Lecture
12,NaN,NaN,NaN,NaN,"Nikpour, Mehdi",09/04/2022,12/01/2022,NaN,A-B1-42,SUN 9:15am-10:15am,Lecture

In [2]:
csvreader = csv.reader(open('Sche.csv'))

header = []
header = next(csvreader)
print(header)

['Course', 'Sect.', 'Description', 'Credits', 'Instructor', 'Start Date', 'End Date', 'Grade', 'Location', 'Days and Times', '']

In [3]:
rows = []
for row in csvreader:
        rows.append(row)

print(row)

['', '', '', '', 'Nikpour, Mehdi', '09/04/2022', '12/01/2022', '', 'A-B1-42', 'SUN 9:15am-10:15am', 'Lecture']

In [4]:
import pandas as pd

data = pd.read_csv("Sche.csv")

In [5]:
data.columns

Index(['Course', 'Sect.', 'Description', 'Credits', 'Instructor', 'Start Date',
       'End Date', 'Grade', 'Location', 'Days and Times', 'Unnamed: 10'],
      dtype='object')

In [6]:
count =0;
while count != len(data):
    if pd.notnull(data.loc[count, 'Course']):
        newC = data.Course[count];
    else:
        data.Course[count] = newC
    count = count +1;


data

/var/folders/kl/fsywh3yd5431b__5bwnlr1h00000gn/T/ipykernel_90377/518265939.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Course[count] = newC

,Course,Sect.,Description,Credits,Instructor,Start Date,End Date,Grade,Location,Days and Times,Unnamed: 10
0,CIV 203,1.0,Ancient World: Humanities,3.0,"Monsma, Frederick",09/04/2022,12/01/2022,***,A-B1-08,MON 9:45am-11:15am,Lecture
1,CIV 203,NaN,NaN,NaN,"Monsma, Frederick",09/04/2022,12/01/2022,NaN,A-B1-08,WED 9:45am-11:15am,Lecture
2,ENG 101,3.0,Argument,3.0,"Danilovich, Stephen",09/04/2022,12/01/2022,***,A-B1-11,TUE 10:30am-11:30am,Lecture
3,ENG 101,NaN,NaN,NaN,"Danilovich, Stephen",09/04/2022,12/01/2022,NaN,A-B1-11,THU 10:30am-11:30am,Lecture
4,ENG 101,NaN,NaN,NaN,"Danilovich, Stephen",09/04/2022,12/01/2022,NaN,A-B1-11,SUN 10:30am-11:30am,Lecture
5,ENGR 344,1.0,Mechanics I,3.0,"Hassan, Aram",09/04/2022,12/01/2022,***,B-F2-31,TUE 1:00pm-2:00pm,Lecture
6,ENGR 344,NaN,NaN,NaN,"Hassan, Aram",09/04/2022,12/01/2022,NaN,B-F2-31,THU 1:00pm-2:00pm,Lecture
7,ENGR 344,NaN,NaN,NaN,"Hassan, Aram",09/04/2022,12/01/2022,NaN,B-F2-31,SUN 1:00pm-2:00pm,Lecture
8,ITE 202,1.0,IT System,3.0,"Lukwesa, Katongo",09/04/2022,12/01/2022,***,B-B1-01,MON 12:30pm-2:00pm,Lecture
9,ITE 202,NaN,NaN,NaN,"Lukwesa, Katongo",09/04/2022,12/01/2022,NaN,B-B1-01,WED 12:30pm-2:00pm,Lecture
10,STT 201,2.0,Statistics,3.0,"Nikpour, Mehdi",09/04/2022,12/01/2022,***,A-B1-42,TUE 9:15am-10:15am,Lecture
11,STT 201,NaN,NaN,NaN,"Nikpour, Mehdi",09/04/2022,12/01/2022,NaN,A-B1-42,THU 9:15am-10:15am,Lecture
12,STT 201,NaN,NaN,NaN,"Nikpour, Mehdi",09/04/2022,12/01/2022,NaN,A-B1-42,SUN 9:15am-10:15am,Lecture

In [7]:

newdat= data['Days and Times'].str.split(' ', expand=True)
time = newdat[1].str.split('-', expand=True)
newdat[1] = time[0]
newdat[2] = time[1]
print(newdat)
size = data.shape[0]
size

      0        1        2
0   MON   9:45am  11:15am
1   WED   9:45am  11:15am
2   TUE  10:30am  11:30am
3   THU  10:30am  11:30am
4   SUN  10:30am  11:30am
5   TUE   1:00pm   2:00pm
6   THU   1:00pm   2:00pm
7   SUN   1:00pm   2:00pm
8   MON  12:30pm   2:00pm
9   WED  12:30pm   2:00pm
10  TUE   9:15am  10:15am
11  THU   9:15am  10:15am
12  SUN   9:15am  10:15am

13

In [8]:
SCOPES = ['https://www.googleapis.com/auth/calendar']

def main(i, data, newdat):
            creds = None
            if os.path.exists('token.json'):                                        #Checks for google account sign in for calander events
                creds = Credentials.from_authorized_user_file('token.json', SCOPES)
        
            if not creds or not creds.valid:
                if creds and creds.expired and creds.refresh_token:
                    creds.refresh(Request())
                else:
                    flow = InstalledAppFlow.from_client_secrets_file(
                        'credintials.json', SCOPES)
                    creds = flow.run_local_server(port=0)
                with open('token.json', 'w') as token:
                    token.write(creds.to_json())

            try:
                date_str = data['Start Date'][i].replace('/','-') 
                Edate_str = data['End Date'][i].replace('/','-') 
                date = datetime.strptime(date_str, '%m-%d-%Y')
                Edate = datetime.strptime(Edate_str, '%m-%d-%Y')
# reformat the date string in the year/mm/dd format
                new_date_str = date.strftime('%Y-%m-%d')
                Enew_date_str = Edate.strftime('%Y-%m-%d')
                print(new_date_str)
                service = build('calendar', 'v3', credentials=creds)
                event = {
                    'summary': data.Course[i],                                         #sets up a calander event based on the class name, location and time
                    'location': data.Location[i],
                    'start': {
                        'dateTime': new_date_str+'T'+newdat[1][i]+':00',
                        'timeZone': 'Etc/GMT-3',
                    },
                    'end': {
                        'dateTime': Enew_date_str+'T'+newdat[2][i]+':00',
                        'timeZone': 'Etc/GMT-3',
                    },
                    'recurrence': [
                        'RRULE:FREQ=WEEKLY;COUNT=14'                    #repeats the instance of every class for 14 weeks
                    ],
                    'reminders': {
                        'useDefault': False,
                        'overrides': [
                        {'method': 'popup', 'minutes': 15},
                        ],
                    },
                    }

                event = service.events().insert(calendarId='primary', body=event).execute()              

            except HttpError as error:
                print('An error occurred: %s' % error)

i =0;
while i != size:
    main(i, data, newdat)
    i = i+1;

2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">
2022-09-04
An error occurred: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json returned "Bad Request". Details: "[{'domain': 'global', 'reason': 'badRequest', 'message': 'Bad Request'}]">

In [9]:
date_str = data['Start Date'][1].replace('/','-') 
Edate_str = data['End Date'][1].replace('/','-') 
date = datetime.strptime(date_str, '%m-%d-%Y')
Edate = datetime.strptime(Edate_str, '%m-%d-%Y')
# reformat the date string in the year/mm/dd format
new_date_str = date.strftime('%Y-%m-%d')
Enew_date_str = Edate.strftime('%Y-%m-%d')\

print(new_date_str)
print(Enew_date_str)

2022-09-04
2022-12-01